### ISSUE TITLE
bug in @ syntax

### ISSUE THREAD

**Issue by houtanb** [DynareTeam/dseries#24]
```
a = dseries(rand(3,3))
a{'Variable_@1,2@'}
a{'Variable_@2@'}
```
The second line works but the third line fails. There is no reason for the third line to fail. One can imagine a user wanting to access multiple dseries but, in doing so, wanting to see one dseries as s/he is working.

**Comment by stepan-a** [comment]
That's not a bug. If one wants to see this particular variable s/he just have to do:
```matlab
a{'Variable_2'}
```

**Comment by houtanb** [comment]
@stepan-a I know. The point is that when working with `dseries` and a group of them using the `@@` notation, you may want to just look at one. We should not ask the user to delete two `@` just to look at this variable only to put them back afterwards. It should not be a big change to make this work and, logically, it should work.

**Comment by stepan-a** [comment]
It's not a big change.. But I do not like it, and I really do not see why someone would want to add unnecessary two `@` symbols to select a single variable. The only situation where it could make a difference is if the calls to `subsref` are written programmatically. In this case it's up to the user to remove the `@`s if there is only one variable name.
