### ISSUE TITLE
modify rename to take one argument

### ISSUE THREAD

**Issue by houtanb** [DynareTeam/dseries#7]
if a ```dseries``` contains only one time series, when using the ```rename``` method, allow it to take just one argument. In this case, that argument will overwrite the name of the only series in the ```dseries```. Useful in this situation (qd is a dseries with multiple series):
```
a = 100*(exp(qd.myseries/100)-1);
a = a.rename('myseries');
```

**Comment by stepan-a** [comment]
@houtanb Okay, I'll do that.

By the way I am not sure anymore that we should keep the current behavior. In the current state the names of the variables change when we apply methods to the object. We could make the name property constant and add another property to keep track of the various transformations of the object. I think we already discussed that, but we should make a decision...

**Comment by houtanb** [comment]
@stepan-a I agree completely. We should keep a constant name and add another field to keep track of the modifications as you say.

**Comment by stepan-a** [comment]
Done in commit  ee49426f21d490a2b9c15f33a72937e296b312c4.
